/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.SessionController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Articulos;
import models.Facturas;

/**
 *
 * @author alvaro
 */
public class TableForeings extends javax.swing.JPanel {
    private final SessionController session_ctrl = new SessionController();
    private String[] columns_name;
    private List registers_list;
    private String id;
    private String table;
    
    /**
     * Creates new form TableForeings
     */
    public TableForeings(String id, String table) {
        initComponents();
        this.id = id;
        this.table = table;
        refreshTableTrue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_foreings = new javax.swing.JTable();
        title_table = new javax.swing.JLabel();

        jtable_foreings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtable_foreings);

        title_table.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        title_table.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(title_table)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(title_table)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void updateTable(Boolean modify_columns) {
        DefaultTableModel model = (DefaultTableModel) jtable_foreings.getModel();
        
        if(modify_columns){
            model.setColumnCount(0);
            
            for(String column : columns_name){
                model.addColumn(column);
            }
        }
        
        model.setRowCount(0);

        for(Object register : registers_list){
            if(register instanceof Facturas){
                Object[] rowData = ((Facturas) register).convertToObjectArray();
                rowData[rowData.length - 2] = null;
                rowData[rowData.length - 1] = null;
                model.addRow(rowData);
            }else if(register instanceof Articulos){
                Object[] rowData = ((Articulos) register).convertToObjectArray();
                rowData[rowData.length - 2] = null;
                rowData[rowData.length - 1] = null;
                model.addRow(rowData);
            }
        }

    }
    
    public void refreshTableTrue(){
        registers_list = session_ctrl.getTableById(id, table);

        if(table.equals("facturas")){
            columns_name = new String[]{"id", "fecha", "total", "metodo de pago"};
        }else{
            columns_name = new String[]{"id", "nombre", "descripción", "stock"};
        }
        updateTable(true);
        title_table.setText(table);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable_foreings;
    private javax.swing.JLabel title_table;
    // End of variables declaration//GEN-END:variables
}
