package models;
// Generated Nov 22, 2023 1:40:19 PM by Hibernate Tools 4.3.1


import interfaces.Identificable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulos generated by hbm2java
 */
public class Articulos  implements java.io.Serializable, Identificable {

    private String idArt;
    private Familias familias;
    private String nomArt;
    private String desArt;
    private BigDecimal stock;
    private Set facturases = new HashSet(0);
    private String[] columns_name = {"id", "nombre", "descripción", "stock", "familias"};

    public Articulos() {
    }

	
    public Articulos(String idArt, String nomArt) {
        this.idArt = idArt;
        this.nomArt = nomArt;
    }
    public Articulos(String idArt, Familias familias, String nomArt, String desArt, BigDecimal stock, Set facturases) {
       this.idArt = idArt;
       this.familias = familias;
       this.nomArt = nomArt;
       this.desArt = desArt;
       this.stock = stock;
       this.facturases = facturases;
    }
   
    public String getIdArt() {
        return this.idArt;
    }
    
    public void setIdArt(String idArt) {
        this.idArt = idArt;
    }
    public Familias getFamilias() {
        return this.familias;
    }
    
    public void setFamilias(Familias familias) {
        this.familias = familias;
    }
    public String getNomArt() {
        return this.nomArt;
    }
    
    public void setNomArt(String nomArt) {
        this.nomArt = nomArt;
    }
    public String getDesArt() {
        return this.desArt;
    }
    
    public void setDesArt(String desArt) {
        this.desArt = desArt;
    }
    public BigDecimal getStock() {
        return this.stock;
    }
    
    public void setStock(BigDecimal stock) {
        this.stock = stock;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }

    public String[] getColumnsName(){
        return this.columns_name;
    }
    
    public Object[] convertToObjectArray(){
        if(familias != null){
            Object[] object_data = {idArt, nomArt, desArt, stock, familias.getIdentificator()};
            return object_data; 
        }else{
            Object[] object_data = {idArt, nomArt, desArt, stock, ""};
            return object_data; 
        }

    }
    
    @Override
    public String getIdentificator() {
        return this.idArt + " - " + this.nomArt;
    }
    
    @Override
    public String toString() {
        return idArt + " - " + nomArt;
    }
}


