package models;
// Generated Nov 22, 2023 1:40:19 PM by Hibernate Tools 4.3.1


import interfaces.Identificable;
import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable, Identificable {

    @Override
    public String toString() {
        return "Clientes{" + "idCli=" + idCli + ", nomCli=" + nomCli + ", correoCli=" + correoCli + ", telCli=" + telCli + ", direcCli=" + direcCli + '}';
    }

    private String idCli;
    private String nomCli;
    private String correoCli;
    private String telCli;
    private String direcCli;
    private Set facturases = new HashSet(0);
    private String[] columns_name = {"id", "nombre", "correo", "teléfono", "dirección", "facturas"};

    public Clientes() {
    }

	
    public Clientes(String idCli, String nomCli) {
        this.idCli = idCli;
        this.nomCli = nomCli;
    }
    public Clientes(String idCli, String nomCli, String correoCli, String telCli, String direcCli, Set facturases) {
       this.idCli = idCli;
       this.nomCli = nomCli;
       this.correoCli = correoCli;
       this.telCli = telCli;
       this.direcCli = direcCli;
       this.facturases = facturases;
    }
   
    public String getIdCli() {
        return this.idCli;
    }
    
    public void setIdCli(String idCli) {
        this.idCli = idCli;
    }
    public String getNomCli() {
        return this.nomCli;
    }
    
    public void setNomCli(String nomCli) {
        this.nomCli = nomCli;
    }
    public String getCorreoCli() {
        return this.correoCli;
    }
    
    public void setCorreoCli(String correoCli) {
        this.correoCli = correoCli;
    }
    public String getTelCli() {
        return this.telCli;
    }
    
    public void setTelCli(String telCli) {
        this.telCli = telCli;
    }
    public String getDirecCli() {
        return this.direcCli;
    }
    
    public void setDirecCli(String direcCli) {
        this.direcCli = direcCli;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }

    public String[] getColumnsName(){
        return this.columns_name;
    }
    
    public Object[] convertToObjectArray(){
        Object[] object_data = {idCli, nomCli, correoCli, telCli, direcCli};
        return object_data;
    }
    
    @Override
    public String getIdentificator() {
        return this.idCli + " - " + this.nomCli;
    }
}


