package models;
// Generated Nov 22, 2023 1:40:19 PM by Hibernate Tools 4.3.1


import interfaces.Identificable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Familias generated by hbm2java
 */
public class Familias  implements java.io.Serializable, Identificable {

    @Override
    public String toString() {
        return "Familias{" + "idFam=" + idFam + ", nomFam=" + nomFam + ", desFam=" + desFam + ", fechaCreacion=" + fechaCreacion + '}';
    }

    private String idFam;
    private String nomFam;
    private String desFam;
    private Date fechaCreacion;
    private Set articuloses = new HashSet(0);
    private String[] columns_name = {"id", "nombre", "descuento", "fecha"};
     
    public Familias() {
    }

	
    public Familias(String idFam, String nomFam) {
        this.idFam = idFam;
        this.nomFam = nomFam;
    }
    public Familias(String idFam, String nomFam, String desFam, Date fechaCreacion, Set articuloses) {
       this.idFam = idFam;
       this.nomFam = nomFam;
       this.desFam = desFam;
       this.fechaCreacion = fechaCreacion;
       this.articuloses = articuloses;
    }
   
    public String getIdFam() {
        return this.idFam;
    }
    
    public void setIdFam(String idFam) {
        this.idFam = idFam;
    }
    public String getNomFam() {
        return this.nomFam;
    }
    
    public void setNomFam(String nomFam) {
        this.nomFam = nomFam;
    }
    public String getDesFam() {
        return this.desFam;
    }
    
    public void setDesFam(String desFam) {
        this.desFam = desFam;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Set getArticuloses() {
        return this.articuloses;
    }
    
    public void setArticuloses(Set articuloses) {
        this.articuloses = articuloses;
    }

    public String[] getColumnsName(){
        return this.columns_name;
    }
    
    public Object[] convertToObjectArray(){
        Object[] object_data = {idFam, nomFam, desFam, fechaCreacion};
        return object_data;
    }
    
    @Override
    public String getIdentificator() {
        return this.idFam + " - " + this.nomFam;
    }
}


